import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import './globals.css';
import '../components/pages/pages.css';
import NavBar from '@/components/navbar/navbar';
import FooterB from '@/components/footer/bottom-footer/footerB';
import ConditionalFooter from '@/components/footer/top-footer/conditionalFooter';

const figtree = Figtree({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={figtree.className}>
      <body className={`antialiased flex flex-col h-screen`}>
        <nav>
          <NavBar />
        </nav>
        <div className="flex flex-col flex-1 items-center">{children}</div>
        <footer>
          <ConditionalFooter />
          <FooterB />
        </footer>
      </body>
    </html>
  );
}
